Fix regression added by XSI-915:
If device is missing during LVM/EXT SR creation we have this error:
```
Error code: SR_BACKEND_FAILURE_1200
Error parameters: , 'LVHDSR' object has no attribute 'root',
```

With this fix we retrieve a more explicit message:
```
Error code: SR_BACKEND_FAILURE_90
Error parameters: , The request is missing the device parameter,
```

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>